/**
 * Registry entries for procedural sources.
 *
 * A procedural source is registered exactly like a book source — the pilot
 * resolves it by id, the manifest index groups by its unit, and its dataset
 * lives under `training-data/<id>/` — but it declares a generator instead of a
 * document parser, and the generator's family is its unit of work (DS008,
 * "Procedural source families"). Keeping the entries in their own module means
 * `teacher/sources/index.mjs` stays a registry of what exists rather than a
 * place where generator wiring accumulates.
 */

export const PROCEDURAL_ARITHMETIC_ID = 'procedural-arithmetic';

/** The generator module path, relative to the repository root, used as the source locator in the inventory. */
export const PROCEDURAL_ARITHMETIC_PATH = 'teacher/procedural/arithmetic.mjs';

export const PROCEDURAL_SOURCES = Object.freeze([
  Object.freeze({
    id: PROCEDURAL_ARITHMETIC_ID,
    kind: 'generated',
    path: PROCEDURAL_ARITHMETIC_PATH,
    generator: 'arithmetic.mjs',
    generatorVersion: '1.2.0',
    // A generated instance has no source text to quarantine: the defects a
    // generator can have (a parse that does not round-trip, an empty oracle, a
    // statement that prints its own answer) are refused when the generator is
    // loaded, before a single file is written.
    quarantineRules: Object.freeze([]),
    seed: 20260921,
    instancesPerFamily: 40,
    assuranceClass: 'constructed_verified',
    unitLabel: 'family',
    unitNoun: 'families',
    unitKind: 'text',
    unitOf: (problem) => problem.familyId,
    manifestFile: (unit) => `family-${unit}.md`,
    secondary: null,
    rights: 'generated by this repository from its own registered generators; no third-party text',
    permittedUse: 'internal training and evaluation; generated material may be redistributed'
  })
]);
